config/routes.rb
Rails.application.routes.draw do
 resources :books
 get 'top' => 'home#top'
 get 'home/about'=> 'home#about'
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index,:edit,:update]

  root 'home#top'

  resources :post_images, only: [:new, :create, :index, :show] do
    resource :post_comments, only: [:create, :destroy]

  get 'posts' => 'posts#index'

end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    validates :body,presence: true
    validates :title,presence: true ,length:{ maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction,length: {  maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
 before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
   root_path # ログアウト後に遷移するpathを設定
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

  def after_sign_in_path_for(resource) 
  	flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)

  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:edit, :destroy,:update]
  def show
     @book = Book.find(params[:id])
     @new_book=Book.new
     @user=current_user
     @user=User.all
  end
  def edit
      @book = Book.find(params[:id])
  end
  def index
     @new_book=Book.new
     @user=current_user
     @books=Book.all
  end
  def create
        flash[:notice] = "You have creatad book successfully"
        @new_book = Book.new(book_params)
        @new_book.user_id = current_user.id
        if @new_book.save
        redirect_to book_path(@new_book.id)
        else
          flash[:notice] = "error"
          @user=current_user
          @books=Book.all
          render :index
        end

  end
  def new
    @book= Book.new

  end
  def update
  
       @book = Book.find(params[:id])
    if @book.update(book_params)
         flash[:notice] = "You have updated book successfully."

    redirect_to book_path(@book.id)
    else 
       flash[:notice] = "error"
      render :edit
  end
  end



  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  private

   def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to books_path
    end
  end

    def book_params
      params.require(:book).permit(:title, :body,:profile_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:edit, :destroy,:update]

 def show
    @users = User.all
    @user = User.find(params[:id])
    @books= @user.books
    @book = Book.new
  end
  def edit
        @user = User.find(params[:id])
    end

  def update
    flash[:notice] = "You have updated user successfully."
    @user = User.find(params[:id])
    if @user.update(user_params)

    redirect_to user_path(@user.id)
    else 
      render :edit
  end
  end


     def index
    @users=User.all
     @user=current_user
     @new_book=Book.new
  end
  private
   def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to user_path(current_user)
    end
  end
 



  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>

<tr>
<td><%= link_to "show", book_path(@book) %></td>
<td><%= link_to "Back", book_path %></td>
</tr>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
       <%= render 'users/list',user: @user, book:@new_book %>
    </div>

    <div class="col-lg-9">

<table class="table table-hover">
  <h2>Books</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
     </tr> 
   </thead>
   <tbody>
    <tr>
      <% @books.each do |book| %>
      <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%=book.body %></td>
    </tr>
     
       <% end %>
       </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
   <html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="v
t" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>



<body>
<div class="container"></div>
  <div class="row">
<div class="col-lg-3">
  <%= render 'users/list',user: @book.user, book:@new_book %>
 </div>

 <div class="col-lg-9">
  <h2>Book detail</h2>

<table class="table table-hover">
   <tbody>
     	<tr>
          <td>  <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                <%= @book.user.name %>
          <%end%>
            
          </td>
                    <td><%= @book.title %></td>
                    <td><%= @book.body %></td>


                    <% if @book.user == current_user %>
                   <td><%= link_to "Edit", edit_book_path(@book) %></td>
        <td><%= link_to "Destory", book_path(@book), method: :delete,  "data-confirm" => '本当に消しますか?' %></td>
        <%end%>
        </tr>
    </tbody>
  </table>
</div>
</div>
</body>
</html> 

app/views/home/about.html.erb
<h1>Welcome to Bookers!</h1>
<p>CopyRight Infratop.inc</p>

app/views/home/top.html.erb
<div class="body">
      <div class="container">
<div class="top-message col-md-offset-3 col-md-6">
          <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In <span class="glyphicon glyphicon-book"></span>
         <strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

   <div class="btn-wrapper">
      <li class=""><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in"
        <%= link_to "login", new_user_session_path %></a>
      </li>
      <li class=""><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" 
        <%= link_to "sign up", new_user_registration_path %></a>
      </li>
     
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<header class="navbar navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
        <span>Bookers</span>
    </nav>
    <nav>
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
        <li class=""><span class="glyphicon glyphicon-home" aria-hidden="true">
        <%= link_to"Home",user_path(current_user.id)%></span>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-user" aria-hidden="true">
        <%= link_to"Users",users_path%></span>
       </li>
      <li class="">
        <span class="glyphicon glyphicon-book" aria-hidden="true">
        <%= link_to"Books", books_path%></span>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-log-out" aria-hidden="true">
        <%= link_to "logout", destroy_user_session_path, method: :delete %></span>
      </li>
    <% else %>
      <li class="">
        <span class="glyphicon glyphicon-home" aria-hidden="true">
        <%= link_to "Home",root_path%></span></li>
      <li class=""><span class="glyphicon glyphicon-link" aria-hidden="true">
        <%= link_to "About",home_about_path%></span></li>
      <li class=""><span class="glyphicon glyphicon-edit" aria-hidden="true">
        <%= link_to "sign up", new_user_registration_path %></span></li>
      <li class=""><span class="glyphicon glyphicon-log-in" aria-hidden="true">
        <%= link_to "login", new_user_session_path %></span></li>
    <% end %>
     </ul>
   </nav>
  </div>
</header>

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
        <%end%>
<body>
    <%= yield %>
</body>
</html>

app/views/post_images/show.html.erb
<li>
  <i class="fa fa-comment"></i>
  <a href="#comments"><%= @post_image.post_comments.count %></a>
</li>
：
：
<div class="comment-list bt style-2" id="comments">
    <div class="float-wrapper">
        <h2 class="comment-count"><%= @post_image.post_comments.count %>件コメント</h2>
    </div>


    <ol>
    <% @post_image.post_comments.each do |post_comment| %>
        <li class="comment">
            <div class="comment-body bb">
                <div class="comment-avatar">
                    <div class="avatar">
                        <%= image_tag('sample-author1.jpg', style: "width: 60px; height: 60px;") %>
                    </div>
                </div>
                <div class="comment-text">
                    <div class="comment-author clearfix">
                        <a href="#" class="link-author"><%= post_comment.user.name %></a>
                        <span class="comment-meta">
                          <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                        </span>
                    </div>
                    <div class="comment-entry"><%= post_comment.comment %></div>
                </div>
            </div>
        </li>
    <% end %>
</ol>

<%= form_for [@post_image, @post_comment] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>


    <ul class="inline-meta">
  <li>By
    <%= post_image.user.name %>
  </li>
  <li>
    <%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %>
  </li>
</ul>

app/views/users/_list.html.erb
<h1>User info</h1>


<div class="profile-container">
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
    <h3 class="profile-name"><%= user.name %></h3>
    <h3 class="profile-introduction"><%= user.introduction %></h3>
  <% if user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(user), class: "pull-right" %></p>
    <% end %>
</div>


<h1>New Book</h1>
<% book.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<%= form_for(book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'create book' %>
<% end %>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1"> 
                            <div class="form-header text-center">
                                <h2 class="form-header-title">User info</h2>
                            </div>
                            <div class="form-body">
                              

                          <%= form_for(@user) do |f| %>

                             <% if @user.errors.any? %>
                             <%= @user.errors.count %>error prohibited this obj from being saved
                             <% @user.errors.full_messages.each do |message| %>
                             <%= message %>
                             <% end %>
                            <% end %>

                            <div class="form-group has-icon">
                              <label class="control-label sr-only" for="inputEmail">Name111</label>
                              <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                                <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>



                               <div class="form-group has-icon">
                               <div class="user-edit-image">
                                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                               </div>

                              <label class="control-label sr-only" for="inputEmail">Image11111</label>
                            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                            
                             <div class="form-group has-icon">
                              <label class="control-label sr-only" for="inputEmail">Introduction</label>
                               <%= f.text_field :introduction,autofocus: true, class:"form-control", id:"inputEmail", placeholder:"introduction"%>
                                 
                                </div>



                            
                          </div> 
                            <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
　　　　　　　　　　　　　　　　　<% end %>
                            </div>
                          </div> 
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render 'users/list',user: @user, book:@new_book %>
    </div>

    <div class="col-lg-9">
            <h2>Users</h2>
             <thead>
            <tr>
            <th>image</th>
            <th>name</th>
              </tr>
          </thead>
       <% @users.each do |user| %>
      

      <table class="table table-hover">
         
          <tbody>
        <tr>
            <td><%= link_to users_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
              <%end%>
            <td><h3 class="profile-name"><%= user.name %></h3></td>
             <td><%= link_to "Show",user_path(user) %></td>
           </tr>
          </tbody>
        </table>
       <% end %>
       </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="v
t" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>




<div class="container">
  <div class="row">
    <div class="col-lg-3">
<h1>User info</h1>
    <h3 class="profile-name"><%= @user.name %></h3>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
    <h3 class="prof-i"><%= @user.introduction %></h3>
  <% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>


<%end%>

<h1>New Book</h1>
<%= form_for(@book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'create book' %>
<% end %>
</div>
<!-- <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> -->


  <div class="col-lg-9">

  <h2>Books</h2>
 
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @books.each do |book| %>
        
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%=book.body %></td>
          <td>
            <%= link_to "Show",book_path(book) %>
             -->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</body>
</html>
  